name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "Sync-Wrap-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: true
    enable_status_monitoring: true
    python_version: ${{ variables.python_version }}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: e2e
      - environment: internal-dev-sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: internal-qa
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: e2e
      - environment: internal-qa-sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: ref
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: int
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              app_id: "84aa2219-7170-4279-93fb-3d37b89bbc01"
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              app_id: "a50e2f01-ea28-41c9-8666-850c034ddd82"
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: prod
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              app_id: "72ada63b-9d70-4ca2-b9f2-cd1ce74c2dde"
              test_type: smoketest
        depends_on:
          - int
          - ref
  