name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    cache_steps:
      - task: s3-cache-action@1
        inputs:
          key: 'node modules | ${{ variables.service_name }}/docker/async-slowapp/package-lock.json'
          location: '${{ variables.service_name }}/docker/async-slowapp/node_modules'
          debug: true
        displayName: cache async-slowapp node modules
      - task: s3-cache-action@1
        inputs:
          key: 'node modules | ${{ variables.service_name }}/docker/sync-wrap/package-lock.json'
          location: '${{ variables.service_name }}/docker/sync-wrap/node_modules'
          debug: true
        displayName: cache sync-wrap node modules
      - task: s3-cache-action@1
        inputs:
          key: 'poetry | ${{ variables.service_name }}/poetry.lock'
          location: '${{ variables.service_name }}/.venv'
          debug: true
        displayName: cache python dependencies
    test_steps:
      - bash: "make test-report"
        displayName: run tests
        workingDirectory: "${{ variables.service_name }}"
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "${{ variables.service_name }}/reports/tests/*.xml"
          failTaskOnFailedTests: true
        displayName: publish test report