name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "Sync-Wrap-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: e2e
      - environment: internal-dev-sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: internal-qa
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: e2e
      - environment: internal-qa-sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: ref
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: int
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              service_name: ${{ variables.service_name }}
        depends_on:
          - internal_qa
      - environment: sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
        depends_on:
          - internal_qa
#       - environment: prod
#         post_deploy:
#           - template: templates/e2e.yml
#             parameters:
#               test_type: smoketest
#         depends_on:
#           - int
#           - ref
