name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    cache_steps:
      - task: s3-cache-action@1
        inputs:
          key: 'node modules | ./docker/async-slowapp/package-lock.json'
          location: './docker/async-slowapp/node_modules'
          debug: true
          workingDirectory: '${{ variables.service_name }}'
        displayName: cache async-slowapp node modules
      - task: s3-cache-action@1
        inputs:
          key: 'node modules | ./docker/sync-wrap/package-lock.json'
          location: './docker/sync-wrap/node_modules'
          debug: true
          workingDirectory: '${{ variables.service_name }}'
        displayName: cache sync-wrap node modules
      - task: s3-cache-action@1
        inputs:
          key: 'poetry | ./poetry.lock'
          location: './.venv'
          debug: true
          workingDirectory: '${{ variables.service_name }}'
        displayName: cache python dependencies
    test_steps:
      - bash: "make test-report"
        displayName: run tests
        workingDirectory: "${{ variables.service_name }}"
      - bash: |
          if [ ! -f "reports/tests/async-slowapp.xml" ] || [ ! -f "reports/tests/sync-wrap.xml" ]; then
            echo "Test reports not found"
            exit -1
          fi
        workingDirectory: ${{ variables.service_name }}
        displayName: Check test reports exist
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "${{ variables.service_name }}/reports/tests/*.xml"
          failTaskOnFailedTests: false
        displayName: publish test report