version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/docker/sync-wrap"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"

