version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/proxies/async-slowapp"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
  - package_manager: "javascript"
    directory: "/proxies/sync-wrap"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"

